name: Push and Pull Request CI
on: 
  push: 
    branches: 
      - main
      - 'releases/**'
    paths: 
      - 'src/**'
  pull_request: 
    branches: 
      - main
      - 'releases/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: src
        run: npm install

      - name: Run tests
        working-directory: src
        run: npm test


        


            